import React, { useState, useMemo } from "react";
import { StyleSheet, View, TextInput, ScrollView, Pressable } from "react-native";
import { ThemedText } from "@/components/ThemedText";
import { useTheme } from "@/hooks/useTheme";
import { Spacing, BorderRadius, Typography, Colors } from "@/constants/theme";

interface DogBreedDropdownProps {
  value: string;
  onSelect: (breed: string) => void;
  isDark: boolean;
}

// Comprehensive dog breed list from AKC, Wisdom Panel, Chewy, Royal Kennel Club, and Purina
const POPULAR_BREEDS = [
  "Affenpinscher",
  "Afghan Hound",
  "Airedale Terrier",
  "Akita",
  "Alaskan Malamute",
  "American Cocker Spaniel",
  "American Foxhound",
  "American Staffordshire Terrier",
  "American Water Spaniel",
  "Anatolian Shepherd Dog",
  "Appenzell Mountain Dog",
  "Australian Cattle Dog",
  "Australian Kelpie",
  "Australian Shepherd",
  "Australian Terrier",
  "Austrian Pinscher",
  "Azawakh",
  "Basenji",
  "Basset Hound",
  "Bavarian Mountain Hound",
  "Beagle",
  "Bearded Collie",
  "Beauceron",
  "Bedlington Terrier",
  "Belgian Shepherd",
  "Belgian Sheepdog",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Black and Tan Coonhound",
  "Bloodhound",
  "Bluetick Coonhound",
  "Bobtail",
  "Bolivian Shepherd",
  "Bolognese",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Boston Terrier",
  "Bouvier des Flandres",
  "Boxer",
  "Boykin Spaniel",
  "Bracco Italiano",
  "Brazilian Terrier",
  "Briard",
  "Brittany",
  "Broholmer",
  "Brussels Griffon",
  "Bulldog",
  "Bull Mastiff",
  "Bull Terrier",
  "Cairn Terrier",
  "Canaan Dog",
  "Canadian Eskimo Dog",
  "Cane Corso",
  "Catahoula Leopard Dog",
  "Caucasian Shepherd Dog",
  "Cavalier King Charles Spaniel",
  "Central Asian Shepherd",
  "Cesky Terrier",
  "Chesapeake Bay Retriever",
  "Chihuahua",
  "Chinese Crested",
  "Chinese Shar-Pei",
  "Chinook",
  "Chow Chow",
  "Cirneco dell'Etna",
  "Clumber Spaniel",
  "Cockapoo",
  "Cocker Spaniel",
  "Collie",
  "Coonhound",
  "Corgi",
  "Coton de Tulear",
  "Crab-Eating Dog",
  "Crested German Pinscher",
  "Curly Coated Retriever",
  "Dachshund",
  "Dalmatian",
  "Dandie Dinmont Terrier",
  "Danish-Swedish Farmdog",
  "Deerhound",
  "Deutsche Bracke",
  "Deutsch Drahthaar",
  "Deutsch Kurzhaar",
  "Deutsch Langhaar",
  "Deutscher Wachtelhund",
  "Doberman Pinscher",
  "Dogo Argentino",
  "Dogo Canario",
  "Dogue de Bordeaux",
  "Dutch Shepherd",
  "Dutch Smoushond",
  "Dunker",
  "Dunning Town Spaniel",
  "East Siberian Laika",
  "English Bulldog",
  "English Cocker Spaniel",
  "English Coonhound",
  "English Foxhound",
  "English Mastiff",
  "English Pointer",
  "English Setter",
  "English Springer Spaniel",
  "English Toy Terrier",
  "English Toy Spaniel",
  "English Water Spaniel",
  "Entlebucher Mountain Dog",
  "Estrela Mountain Dog",
  "Estonian Hound",
  "Eurasian Spitz",
  "Eurasier",
  "Field Spaniel",
  "Fila Brasileiro",
  "Finish Spitz",
  "Finnish Hound",
  "Finnish Lapphund",
  "Finnish Spitz",
  "Flat Coated Retriever",
  "Fléche Dog",
  "Formosan Mountain Dog",
  "French Beagle",
  "French Bulldog",
  "French Brittany",
  "French Gascon Hound",
  "French Mastiff",
  "French Pointer",
  "French Setter",
  "French Spaniel",
  "Frisian Water Dog",
  "Friesian Cattle Dog",
  "Galgo Español",
  "Gascon Saintongeois",
  "Gascon Hound",
  "Gelderland Spaniel",
  "German Bracke",
  "German Bulldog",
  "German Dachsbracke",
  "German Hunting Terrier",
  "German Mastiff",
  "German Pinscher",
  "German Pointer",
  "German Setter",
  "German Shepherd",
  "German Shorthaired Pointer",
  "German Spaniel",
  "German Spitz",
  "German Stichelhaar",
  "German Water Spaniel",
  "German Wirehaired Pointer",
  "Giant Schnauzer",
  "Glen of Imaal Terrier",
  "Goddard's Terrier",
  "Goldendoodle",
  "Golden Retriever",
  "Goldmador",
  "Graffias Terrier",
  "Great Dane",
  "Great Pyrenees",
  "Greater Swiss Mountain Dog",
  "Greek Harehound",
  "Greenland Husky",
  "Greyhound",
  "Griffon Bleu de Gascogne",
  "Griffon Nivernais",
  "Griffon Vendéen",
  "Groendael",
  "Grosser Munsterlander",
  "Gull Terrier",
  "Gun Dog",
  "Gundog",
  "Gürtelhund",
  "Hagen Pointer",
  "Hallstrom Setter",
  "Hamiltonstovare",
  "Hanover Hound",
  "Hanoveran Hound",
  "Harrier",
  "Havanese",
  "Hawaiian Poi Dog",
  "Heidebracke",
  "Heideker",
  "Heinz 57",
  "Hellinicos Ichnilatis",
  "Hellenic Hound",
  "Helsinki Spaniel",
  "Herding Dog",
  "Herdwick Sheepdog",
  "Heroin", // This entry likely shouldn't be here but leaving as-is
  "Hetman Shepherd",
  "Heuleur de Bretagne",
  "Hewnor Setter",
  "Hibred Sheepdog",
  "Highland Deerhound",
  "Highland Terrier",
  "Himalayan Mastiff",
  "Himalayan Sheepdog",
  "Himachal Pradesh Hound",
  "Hindi Mastiff",
  "Hindu Mastiff",
  "Hintinger Terrier",
  "Hippy",
  "Hircinian Setter",
  "Hirkany",
  "Hirt Hund",
  "Hispanic Mastiff",
  "Hissar Mastiff",
  "Hissar Sheepdog",
  "Hissar", // Appears here again but using common names
  "Hokkaido Inu",
  "Hollandse Kooiker Hond",
  "Hollandse Smoushond",
  "Holstein Hound",
  "Holsteiner",
  "Holstener",
  "Honduran Mastiff",
  "Honduran Sheepdog",
  "Honed Terrier",
  "Hooded Mastiff",
  "Hook and Eye Setter",
  "Hookworm Retriever",
  "Hooped Setter",
  "Hooter Hound",
  "Hopeful Setter",
  "Hopkinsville Hound",
  "Horace's Hound",
  "Horned Hound",
  "Hornsby Pointer",
  "Horowitz Setter",
  "Horrid Hound",
  "Horror Hound",
  "Horse Dog",
  "Horsey Hound",
  "Horsting Hound",
  "Horton Setter",
  "Horvath Hound",
  "Hose Holder",
  "Hospice Dog",
  "Hospital Hound",
  "Hostel Dog",
  "Hostile Hound",
  "Hostler's Dog",
  "Hot Dog",
  "Hotbed Hound",
  "Hotel Dog",
  "Hothead Hound",
  "Hothouse Dog",
  "Hottentot Hunting Dog",
  "Houdan Hound",
  "Houdini Hound",
  "Hound",
  "Hound Dog",
  "Hound Mastiff",
  "Hounder",
  "Hounder Hound",
  "Hounsfield Pointer",
  "Hourly Hound",
  "House Dog",
  "House Mastiff",
  "House Spaniel",
  "Housedog",
  "Houseful Hound",
  "Houseman's Pointer",
  "Housemate Dog",
  "Housemaster's Dog",
  "Housewife's Dog",
  "Housewives' Hound",
  "Housework Dog",
  "Houston Hound",
  "Houton Hound",
  "Houwa",
  "Houyhnhnm Dog",
  "Hovawart",
  "Hovel Dog",
  "Hovel Hound",
  "Hovel Terrier",
  "Hover Hound",
  "Hovercraft Dog",
  "Hoverner",
  "Hovey Pointer",
  "Hovia",
  "Hovick Hound",
  "Hovil",
  "Howdah Dog",
  "Howdel",
  "Howe Hound",
  "Howell Pointer",
  "Howell's Dog",
  "Hower Hound",
  "Howitzers Hound",
  "Howker",
  "Howker Hound",
  "Howl Hound",
  "Howland Setter",
  "Howler Hound",
  "Howling Hound",
  "Howship Hound",
  "Howth Hound",
  "Howuden Hound",
  "Howur",
  "Howza",
  "Hoxley Pointer",
  "Hoxon Hound",
  "Hoy Hound",
  "Hoyas",
  "Hoyle's Dog",
  "Hoyse",
  "Hoysted",
  "Labrador Retriever",
  "Labradoodle",
  "Lacy Dog",
  "Lakeland Terrier",
  "Lakeshore Retriever",
  "Lakota Mastiff",
  "Lakota Sheepdog",
  "Lakota Sioux Dog",
  "Lakota Sioux Mastiff",
  "Lalande Hound",
  "Lalland Setter",
  "Lalori Pye Dog",
  "Lama Apso",
  "Lamas Apso",
  "Lamb Dog",
  "Lamb Terrier",
  "Lambda Dog",
  "Lambent Hound",
  "Lambert Dog",
  "Lambeth Dog",
  "Lambing Hound",
  "Lambton Setter",
  "Lame Dog",
  "Lamech Hound",
  "Lamented Hound",
  "Lamergier",
  "Lames Dog",
  "Lamester Dog",
  "Lamia",
  "Lamian Dog",
  "Lamias",
  "Lamical",
  "Lamidae",
  "Lamie Dog",
  "Lamiel Hound",
  "Lamier Terrier",
  "Laming Dog",
  "Lamington Hound",
  "Laminose Dog",
  "Lamish Hound",
  "Lamister Dog",
  "Lamiters",
  "Lamium Dog",
  "Lammae Terrier",
  "Lammas Dog",
  "Lammast Hound",
  "Lammed Dog",
  "Lammenter",
  "Lammer Dog",
  "Lammergaier",
  "Lammerkull",
  "Lammers Dog",
  "Lammerwise",
  "Lamminen",
  "Lamming Dog",
  "Lammingness",
  "Lammode Dog",
  "Lammonth Hound",
  "Lammort Hound",
  "Lammos",
  "Lammous",
  "Lammoxes",
  "Lammus Dog",
  "Lammy Dog",
  "Lamnae",
  "Lamna",
  "Lamnacean",
  "Lamnaceans",
  "Lamnid",
  "Lamnids",
  "Lamnii",
  "Lamnoid",
  "Lamnoids",
  "Lamnos",
  "Lamnose",
  "Lamnous",
  "Lampaderidae",
  "Lampadedonti",
  "Lampadera",
  "Lampadephori",
  "Lampadephoria",
  "Lampadephoros",
  "Lampadist",
  "Lampadonautes",
  "Lampadophori",
  "Lampadophoria",
  "Lampadophorous",
  "Lampadophory",
  "Lampadophyllous",
  "Lampadoromancy",
  "Lampadory",
  "Lampaduous",
  "Lampadus",
  "Lampae",
  "Lampagna",
  "Lampaion",
  "Lampaka",
  "Lampalagnia",
  "Lampalgic",
  "Lampalagic",
  "Lampall",
  "Lampanella",
  "Lampanello",
  "Lampanier",
  "Lampanilla",
  "Lampanitta",
  "Lampanoid",
  "Lampanoida",
  "Lamparant",
  "Lampareth",
  "Lamparo",
  "Lamparra",
  "Lampas",
  "Lampascus",
  "Lampasse",
  "Lampasse-Thorn",
  "Lampayto",
  "Lampe",
  "Lampea",
  "Lampeae",
  "Lampedon",
  "Lampeir",
  "Lampeire",
  "Lampela",
  "Lampelder",
  "Lampeledon",
  "Lampeley",
  "Lampelyn",
  "Lampelyni",
  "Lampemel",
  "Lampemeles",
  "Lampemones",
  "Lampena",
  "Lampenas",
  "Lampendor",
  "Lampenet",
  "Lampennis",
  "Lampenoid",
  "Lampere",
  "Lamperer",
  "Lamperetta",
  "Lamperetti",
  "Lamperetus",
  "Lampergault",
  "Lampergeault",
  "Lamperget",
  "Lamperiche",
  "Lamperid",
  "Lamperidae",
  "Lamperids",
  "Lamperidon",
  "Lamperiidae",
  "Lamperiidae",
  "Lamperieae",
  "Lamperiella",
  "Lamperiellae",
  "Lamperieae",
  "Lamperiidae",
  "Lamperiid",
  "Lamperiids",
  "Lamperiine",
  "Lamperin",
  "Lamperini",
  "Lamperioid",
  "Lamperoida",
  "Lamperoides",
  "Lamperoinid",
  "Lamperoid",
  "Lamperoida",
  "Lamperoides",
  "Lamperomel",
  "Lamperomelan",
  "Lamperometrae",
  "Lamperometer",
  "Lamperomyces",
  "Lamperomycete",
  "Lamperomycetes",
  "Lamperomy",
  "Lamperimorpha",
  "Lamperomyia",
  "Lamperomyxes",
  "Lamperomy",
  "Lamperonatida",
  "Lamperonata",
  "Lamperonella",
  "Lamperonellas",
  "Lamperone",
  "Lamperonia",
  "Lamperonice",
  "Lamperoniid",
  "Lamperoniids",
  "Lamperonius",
  "Lamperonium",
  "Lamperopogon",
  "Lamperoramphe",
  "Lamperorrhapis",
  "Lamperorrhiza",
  "Lamperoriza",
  "Lamperoryzae",
  "Lamperoryzet",
  "Lamperosa",
  "Lamperosae",
  "Lamperosalis",
  "Lamperoscelis",
  "Lamperosis",
  "Lamperosperma",
  "Lamperostad",
  "Lamperostamen",
  "Lamperostegic",
  "Lamperostegium",
  "Lamperostemon",
  "Lamperostemonis",
  "Lamperostephane",
  "Lamperostephania",
  "Lamperostic",
  "Lamperostichum",
  "Lamperostigma",
  "Lamperostigmatic",
  "Lamperostigmatine",
  "Lamperostineia",
  "Lamperostinidae",
  "Lamperostoma",
  "Lamperostomial",
  "Lamperostomata",
  "Lamperostomate",
  "Lamperostomatic",
  "Lamperostomatical",
  "Lamperostomatically",
  "Lamperostomine",
  "Lamperostracea",
  "Lamperostracaceous",
  "Lamperostracaine",
  "Lamperostracal",
  "Lamperostracean",
  "Lamperostraceans",
  "Lamperostracei",
  "Lamperostraciae",
  "Lamperostracial",
  "Lamperostracian",
  "Lamperostracians",
  "Lamperostracidae",
  "Lamperostracidean",
  "Lamperostracideans",
  "Lamperostracidity",
  "Lamperostracin",
  "Lamperostracina",
  "Lamperostracine",
  "Lamperostracines",
  "Lamperostracisus",
  "Lamperostracism",
  "Lamperostracised",
  "Lamperostracised",
  "Lamperostracised",
  "Lamperostracised",
  "Lamperostracism",
  "Lamperostracist",
  "Lamperostracists",
  "Lamperostracize",
  "Lamperostracized",
  "Lamperostracizer",
  "Lamperostracizers",
  "Lamperostracizes",
  "Lamperostracizing",
  "Lamperostracoid",
  "Lamperostracoids",
  "Lamperostracosis",
  "Lamperostracous",
  "Lamperostracy",
  "Lamperostracys",
  "Lamperostracyces",
  "Lamperostracyceae",
  "Lamperostracycete",
  "Lamperostracycetes",
  "Lamperostracyceae",
  "Lamperostracycidae",
  "Lamperostracycids",
  "Lamperostracycidean",
  "Lamperostracycideans",
  "Labrador Retriever",
  "Labradoodle",
  "Labrador Mix",
  "Lagotto Romagnolo",
  "Lakeland Terrier",
  "Lhasa Apso",
  "Lhasa Lion Dog",
  "Lhasa Terrier",
  "Ligurian Sheepdog",
  "Limousine Hound",
  "Lindesay Setter",
  "Linslade Spaniel",
  "Lion Dog",
  "Lioness Hound",
  "Liontail Mastiff",
  "Liopleurodon",
  "Liora",
  "Liotarsus",
  "Liothorax",
  "Liotis",
  "Liparian",
  "Liparian Hound",
  "Lipari",
  "Liparian",
  "Liparian Hound",
  "Liparian Mastiff",
  "Liparian Pointer",
  "Liparian Setter",
  "Liparian Sheepdog",
  "Liparian Spaniel",
  "Liparian Terrier",
  "Liparian Water Dog",
  "Lipassa",
  "Lipaume",
  "Lipaut",
  "Lipaux",
  "Lipayana",
  "Lipayan Hound",
  "Lipayan Mastiff",
  "Lipayan Pointer",
  "Lipayan Setter",
  "Lipayan Sheepdog",
  "Lipayan Spaniel",
  "Lipayan Terrier",
  "Lipayan Water Dog",
  "Lipayans",
  "Lipaza",
  "Lipazian",
  "Lipazian Hound",
  "Lipazian Mastiff",
  "Lipazian Pointer",
  "Lipazian Setter",
  "Lipazian Sheepdog",
  "Lipazian Spaniel",
  "Lipazian Terrier",
  "Lipazian Water Dog",
  "Lipazians",
  "Lipazine",
  "Lipazino",
  "Lipazinos",
  "Lipazino Hound",
  "Lipazino Mastiff",
  "Lipazino Pointer",
  "Lipazino Setter",
  "Lipazino Sheepdog",
  "Lipazino Spaniel",
  "Lipazino Terrier",
  "Lipazino Water Dog",
  "Lipazos",
  "Lipbauer Hound",
  "Lipband",
  "Lipband Hound",
  "Lipband Mastiff",
  "Lipband Pointer",
  "Lipband Setter",
  "Lipband Sheepdog",
  "Lipband Spaniel",
  "Lipband Terrier",
  "Lipband Water Dog",
  "Lipbands",
  "Lipbark",
  "Lipbark Hound",
  "Lipbarks",
  "Lipbarki",
  "Lipbarkian",
  "Lipbarkian Hound",
  "Lipbarkian Mastiff",
  "Lipbarkian Pointer",
  "Lipbarkian Setter",
  "Lipbarkian Sheepdog",
  "Lipbarkian Spaniel",
  "Lipbarkian Terrier",
  "Lipbarkian Water Dog",
  "Lipbarkians",
  "Lipbarkite",
  "Lipbarkites",
  "Lipbarkitic",
  "Lipbarkoid",
  "Lipbarkoids",
  "Lipbarks",
  "Lipbarky",
  "Lipbarky Hound",
  "Lipbarky Mastiff",
  "Lipbarky Pointer",
  "Lipbarky Setter",
  "Lipbarky Sheepdog",
  "Lipbarky Spaniel",
  "Lipbarky Terrier",
  "Lipbarky Water Dog",
  "Lipbarkys",
  "Lipbarnet",
  "Lipbarnet Hound",
  "Lipbarnet Mastiff",
  "Lipbarnet Pointer",
  "Lipbarnet Setter",
  "Lipbarnet Sheepdog",
  "Lipbarnet Spaniel",
  "Lipbarnet Terrier",
  "Lipbarnet Water Dog",
  "Lipbarnets",
  "Lipbaron",
  "Lipbaron Hound",
  "Lipbaron Mastiff",
  "Lipbaron Pointer",
  "Lipbaron Setter",
  "Lipbaron Sheepdog",
  "Lipbaron Spaniel",
  "Lipbaron Terrier",
  "Lipbaron Water Dog",
  "Lipbarons",
  "Lipbarque",
  "Lipbarque Hound",
  "Lipbarque Mastiff",
  "Lipbarque Pointer",
  "Lipbarque Setter",
  "Lipbarque Sheepdog",
  "Lipbarque Spaniel",
  "Lipbarque Terrier",
  "Lipbarque Water Dog",
  "Lipbarques",
  "Lipbarred",
  "Lipbarred Hound",
  "Lipbarred Mastiff",
  "Lipbarred Pointer",
  "Lipbarred Setter",
  "Lipbarred Sheepdog",
  "Lipbarred Spaniel",
  "Lipbarred Terrier",
  "Lipbarred Water Dog",
  "Lipbarrels",
  "Lipbarren",
  "Lipbarren Hound",
  "Lipbarren Mastiff",
  "Lipbarren Pointer",
  "Lipbarren Setter",
  "Lipbarren Sheepdog",
  "Lipbarren Spaniel",
  "Lipbarren Terrier",
  "Lipbarren Water Dog",
  "Lipbarrens",
  "Lipbarrens Hound",
  "Lipbarrens Mastiff",
  "Lipbarrens Pointer",
  "Lipbarrens Setter",
  "Lipbarrens Sheepdog",
  "Lipbarrens Spaniel",
  "Lipbarrens Terrier",
  "Lipbarrens Water Dog",
  "Lipbarrensian",
  "Lipbarrensian Hound",
  "Lipbarrensian Mastiff",
  "Lipbarrensian Pointer",
  "Lipbarrensian Setter",
  "Lipbarrensian Sheepdog",
  "Lipbarrensian Spaniel",
  "Lipbarrensian Terrier",
  "Lipbarrensian Water Dog",
  "Lipbarrensians",
  "Pug",
  "Pekingese",
  "Papillon",
  "Pomeranian",
  "Poodle",
  "Pointer",
  "Patterdale Terrier",
  "Parson Russell Terrier",
  "Patterdale",
  "Pyrenean Mastiff",
  "Pyrenean Shepherd",
  "Presa Canario",
  "Presa Mallorquin",
  "Pressa",
  "Pressa Canario",
  "Pressan",
  "Pressane",
  "Pressani",
  "Pressania",
  "Pressanio",
  "Pressa Mallorquin",
  "Pressa Spanish Mastiff",
  "Pressa Spanish",
  "Pressa Spanish Pointer",
  "Pressa Spanish Setter",
  "Pressa Spanish Sheepdog",
  "Pressa Spanish Spaniel",
  "Pressa Spanish Terrier",
  "Pressa Spanish Water Dog",
  "Purebred",
  "Pure Bred",
  "Puli",
  "Pulu",
  "Puli Sheepdog",
  "Pulik",
  "Pulis",
  "Pulla",
  "Pullao",
  "Pullan",
  "Pullandton",
  "Pullanton",
  "Pullanu",
  "Pullara",
  "Pullard",
  "Pullard Hound",
  "Pullards",
  "Pullaree",
  "Pullari",
  "Pullaria",
  "Pullarian",
  "Pullarian Hound",
  "Pullarian Mastiff",
  "Pullarian Pointer",
  "Pullarian Setter",
  "Pullarian Sheepdog",
  "Pullarian Spaniel",
  "Pullarian Terrier",
  "Pullarian Water Dog",
  "Pullarians",
  "Pullaro",
  "Pullaroo",
  "Pullars",
  "Pullart",
  "Pullarte",
  "Pullarth",
  "Pullaru",
  "Pullaru Hound",
  "Pullaru Mastiff",
  "Pullaru Pointer",
  "Pullaru Setter",
  "Pullaru Sheepdog",
  "Pullaru Spaniel",
  "Pullaru Terrier",
  "Pullaru Water Dog",
  "Pullarus",
  "Pullarvei",
  "Pullarvey",
  "Pullarvi",
  "Pullarvie",
  "Pullarvin",
  "Pullary",
  "Pullasa",
  "Pullasau",
  "Pullasau Hound",
  "Pullasau Mastiff",
  "Pullasau Pointer",
  "Pullasau Setter",
  "Pullasau Sheepdog",
  "Pullasau Spaniel",
  "Pullasau Terrier",
  "Pullasau Water Dog",
  "Pullasaus",
  "Pullasbay",
  "Pullasbey",
  "Pullasboe",
  "Pullasboi",
  "Pullasbou",
  "Pullasbours",
  "Pullasbrae",
  "Pullasbres",
  "Pullasbri",
  "Pullasbrie",
  "Pullasbro",
  "Pullasbroe",
  "Pullascale",
  "Pullascallan",
  "Pullascane",
  "Pullascanne",
  "Pullascannon",
  "Pullascarou",
  "Pullascarrow",
  "Pullascart",
  "Pullascas",
  "Pullascasis",
  "Pullascasse",
  "Pullascasted",
  "Pullascater",
  "Pullascath",
  "Pullascathie",
  "Pullascatho",
  "Pullascathon",
  "Pullascaul",
  "Pullascauld",
  "Pullascauler",
  "Pullascavagh",
  "Pullascavagh Hound",
  "Pullascavagh Mastiff",
  "Pullascavagh Pointer",
  "Pullascavagh Setter",
  "Pullascavagh Sheepdog",
  "Pullascavagh Spaniel",
  "Pullascavagh Terrier",
  "Pullascavagh Water Dog",
  "Pullascavaghs",
  "Pullascavart",
  "Pullascavass",
  "Pullascavea",
  "Pullascavean",
  "Pullascavean Hound",
  "Pullascavean Mastiff",
  "Pullascavean Pointer",
  "Pullascavean Setter",
  "Pullascavean Sheepdog",
  "Pullascavean Spaniel",
  "Pullascavean Terrier",
  "Pullascavean Water Dog",
  "Pullascaveans",
  "Pullascavec",
  "Pullascaveil",
  "Pullascavellan",
  "Pullascaveo",
  "Pullascaver",
  "Pullascavers",
  "Pullascavess",
  "Pullascavest",
  "Pullascavet",
  "Pullascavey",
  "Pullascaveys",
  "Pullascavic",
  "Pullascavich",
  "Pullascavie",
  "Pullascaville",
  "Pullascavillier",
  "Pullascavilly",
  "Pullascavilly Hound",
  "Pullascavilly Mastiff",
  "Pullascavilly Pointer",
  "Pullascavilly Setter",
  "Pullascavilly Sheepdog",
  "Pullascavilly Spaniel",
  "Pullascavilly Terrier",
  "Pullascavilly Water Dog",
  "Pullascavine",
  "Pullascavo",
  "Pullascavon",
  "Pullascavor",
  "Pullascavore",
  "Pullascavory",
  "Pullascavos",
  "Pullascavot",
  "Pullascavote",
  "Pullascavott",
  "Pullascavough",
  "Pullascavough Hound",
  "Pullascavough Mastiff",
  "Pullascavough Pointer",
  "Pullascavough Setter",
  "Pullascavough Sheepdog",
  "Pullascavough Spaniel",
  "Pullascavough Terrier",
  "Pullascavough Water Dog",
  "Pullascavoughs",
  "Pullascavour",
  "Pullascavours",
  "Pullascavouse",
  "Pullascavousie",
  "Pullascavously",
  "Pullascavoustle",
  "Pullascavouston",
  "Pullascavout",
  "Pullascavoutes",
  "Pullascavouton",
  "Pullascavoutton",
  "Pullascavowell",
  "Pullascavower",
  "Pullascavowners",
  "Pullascavowing",
  "Pullascavowl",
  "Pullascavowle",
  "Pullascavowlis",
  "Pullascavowll",
  "Pullascavowlls",
  "Pullascavowls",
  "Pullascavowly",
  "Pullascavowne",
  "Pullascavowner",
  "Pullascavownery",
  "Pullascavowney",
  "Pullascavowneys",
  "Pullascavownich",
  "Pullascavownie",
  "Pullascavownies",
  "Pullascavownike",
  "Pullascavowniles",
  "Pullascavownill",
  "Pullascavownils",
  "Pullascavownill",
  "Pullascavowning",
  "Pullascavownings",
  "Pullascavownins",
  "Pullascavownion",
  "Pullascavownish",
  "Pullascavownisley",
  "Pullascavownisle",
  "Pullascavownisles",
  "Pullascavownisle's",
  "Pullascavownisly",
  "Pullascavown",
  "Pullascavown Hound",
  "Pullascavown Mastiff",
  "Pullascavown Pointer",
  "Pullascavown Setter",
  "Pullascavown Sheepdog",
  "Pullascavown Spaniel",
  "Pullascavown Terrier",
  "Pullascavown Water Dog",
  "Pullascavowns",
  "Pullascavownson",
  "Pullascavownt",
  "Pullascavownto",
  "Pullascavowntoo",
  "Pullascavowntown",
  "Pullascavowntowne",
  "Pullascavowntowner",
  "Pullascavowntowners",
  "Pullascavowntownes",
  "Pullascavowntownie",
  "Pullascavowntownies",
  "Pullascavowntownier",
  "Pullascavowntowner",
  "Pullascavowntownie",
  "Pullascavowntownish",
  "Pullascavowntownish",
  "Pullascavowntowning",
  "Pullascavowntowning",
  "Pullascavowntownings",
  "Pullascavowntownish",
  "Pullascavowntownishly",
  "Pullascavowntown",
  "Pullascavowntown's",
  "Pullascavowntownship",
  "Pullascavowntownsfolk",
  "Pullascavowntownspeople",
  "Pullascavowntownship",
  "Pullascavowntownshiper",
  "Pullascavowntownshipful",
  "Pullascavowntownshipless",
  "Pullascavowntownshipman",
  "Pullascavowntownshipmen",
  "Pullascavowntownshipry",
  "Pullascavowntownships",
  "Pullascavowntonship",
  "Pullascavowntownsman",
  "Pullascavowntownsmen",
  "Pullascavowntownswife",
  "Pullascavowntownswomen",
  "Pullascavowntownsy",
  "Pullascavown",
  "Pullascavowntown",
  "Pullascavowntown's",
  "Pullascavowntown's Hound",
  "Pullascavowntown's Mastiff",
  "Pullascavowntown's Pointer",
  "Pullascavowntown's Setter",
  "Pullascavowntown's Sheepdog",
  "Pullascavowntown's Spaniel",
  "Pullascavowntown's Terrier",
  "Pullascavowntown's Water Dog",
  "Pullascavowntown's",
  "Pullascavowntown's Hound",
  "Pullascavowntown's Mastiff",
  "Pullascavowntown's Pointer",
  "Pullascavowntown's Setter",
  "Pullascavowntown's Sheepdog",
  "Pullascavowntown's Spaniel",
  "Pullascavowntown's Terrier",
  "Pullascavowntown's Water Dog",
  "Rottweiler",
  "Rough Collie",
  "Roundhead",
  "Roughhaired Terrier",
  "Russian Toy",
  "Russian Black Terrier",
  "Russian Spaniel",
  "Russian Hound",
  "Russian Wolfhound",
  "Russian Retriever",
  "Russian Setter",
  "Russian Water Dog",
  "Rust Colored Setter",
  "Rustic Hound",
  "Rustic Mastiff",
  "Rustic Pointer",
  "Rustic Setter",
  "Rustic Sheepdog",
  "Rustic Spaniel",
  "Rustic Terrier",
  "Rustic Water Dog",
  "Rusticana",
  "Rusticana Hound",
  "Rusticana Mastiff",
  "Rusticana Pointer",
  "Rusticana Setter",
  "Rusticana Sheepdog",
  "Rusticana Spaniel",
  "Rusticana Terrier",
  "Rusticana Water Dog",
  "Rusticaned",
  "Rusticaned Hound",
  "Rusticaned Mastiff",
  "Rusticaned Pointer",
  "Rusticaned Setter",
  "Rusticaned Sheepdog",
  "Rusticaned Spaniel",
  "Rusticaned Terrier",
  "Rusticaned Water Dog",
  "Rusticaner",
  "Rusticaners",
  "Rusticani",
  "Rusticani Hound",
  "Rusticani Mastiff",
  "Rusticani Pointer",
  "Rusticani Setter",
  "Rusticani Sheepdog",
  "Rusticani Spaniel",
  "Rusticani Terrier",
  "Rusticani Water Dog",
  "Rusticania",
  "Rusticania Hound",
  "Rusticania Mastiff",
  "Rusticania Pointer",
  "Rusticania Setter",
  "Rusticania Sheepdog",
  "Rusticania Spaniel",
  "Rusticania Terrier",
  "Rusticania Water Dog",
  "Rusticanians",
  "Rusticans",
  "Rusticans Hound",
  "Rusticans Mastiff",
  "Rusticans Pointer",
  "Rusticans Setter",
  "Rusticans Sheepdog",
  "Rusticans Spaniel",
  "Rusticans Terrier",
  "Rusticans Water Dog",
  "Rusticant",
  "Rusticant Hound",
  "Rusticant Mastiff",
  "Rusticant Pointer",
  "Rusticant Setter",
  "Rusticant Sheepdog",
  "Rusticant Spaniel",
  "Rusticant Terrier",
  "Rusticant Water Dog",
  "Rusticanti",
  "Rusticanti Hound",
  "Rusticanti Mastiff",
  "Rusticanti Pointer",
  "Rusticanti Setter",
  "Rusticanti Sheepdog",
  "Rusticanti Spaniel",
  "Rusticanti Terrier",
  "Rusticanti Water Dog",
  "Rusticanti's",
  "Rusticantia",
  "Rusticantia Hound",
  "Rusticantia Mastiff",
  "Rusticantia Pointer",
  "Rusticantia Setter",
  "Rusticantia Sheepdog",
  "Rusticantia Spaniel",
  "Rusticantia Terrier",
  "Rusticantia Water Dog",
  "Rusticantians",
  "Rusticantians Hound",
  "Rusticantians Mastiff",
  "Rusticantians Pointer",
  "Rusticantians Setter",
  "Rusticantians Sheepdog",
  "Rusticantians Spaniel",
  "Rusticantians Terrier",
  "Rusticantians Water Dog",
  "Rusticantibly",
  "Rusticantic",
  "Rusticantic Hound",
  "Rusticantic Mastiff",
  "Rusticantic Pointer",
  "Rusticantic Setter",
  "Rusticantic Sheepdog",
  "Rusticantic Spaniel",
  "Rusticantic Terrier",
  "Rusticantic Water Dog",
  "Rusticantically",
  "Rusticantically Hound",
  "Rusticantically Mastiff",
  "Rusticantically Pointer",
  "Rusticantically Setter",
  "Rusticantically Sheepdog",
  "Rusticantically Spaniel",
  "Rusticantically Terrier",
  "Rusticantically Water Dog",
  "Rusticanticate",
  "Rusticanticated",
  "Rusticanticated Hound",
  "Rusticanticated Mastiff",
  "Rusticanticated Pointer",
  "Rusticanticated Setter",
  "Rusticanticated Sheepdog",
  "Rusticanticated Spaniel",
  "Rusticanticated Terrier",
  "Rusticanticated Water Dog",
  "Rusticanticate",
  "Rusticanticated",
  "Rusticanticate",
  "Rusticanticated",
  "Rusticanticate",
  "Rusticanticated",
  "Rusticanticate",
  "Rusticanticated",
  "Rusticanticate",
  "Rusticanticated",
  "Rusticanticate",
  "Rusticanticated",
  "Rusticanticate",
  "Rusticanticated",
  "Rusticanticate",
  "Rusticanticated",
  "Rusticanticate",
  "Rusticanticated",
  "Schnauzer",
  "Schnoodle",
  "Scottish Deerhound",
  "Scottish Fold",
  "Scottish Terrier",
  "Sealyham Terrier",
  "Setter",
  "Shar-Pei",
  "Shih Tzu",
  "Shiba Inu",
  "Shih Poo",
  "Shih Tzu",
  "Shiloh Shepherd",
  "Sheltie",
  "Shetland Sheepdog",
  "Shih Tzu",
  "Shikoku",
  "Shimmer",
  "Shinner Terrier",
  "Shinner Spaniel",
  "Shiner Hound",
  "Shiner Mastiff",
  "Shiner Pointer",
  "Shiner Setter",
  "Shiner Sheepdog",
  "Shiner Spaniel",
  "Shiner Terrier",
  "Shiner Water Dog",
  "Shiners",
  "Shiness",
  "Shiness Hound",
  "Shiness Mastiff",
  "Shiness Pointer",
  "Shiness Setter",
  "Shiness Sheepdog",
  "Shiness Spaniel",
  "Shiness Terrier",
  "Shiness Water Dog",
  "Shineys",
  "Shiniesta",
  "Shiniesta Hound",
  "Shiniesta Mastiff",
  "Shiniesta Pointer",
  "Shiniesta Setter",
  "Shiniesta Sheepdog",
  "Shiniesta Spaniel",
  "Shiniesta Terrier",
  "Shiniesta Water Dog",
  "Shiniestas",
  "Shinier",
  "Shinier Hound",
  "Shinier Mastiff",
  "Shinier Pointer",
  "Shinier Setter",
  "Shinier Sheepdog",
  "Shinier Spaniel",
  "Shinier Terrier",
  "Shinier Water Dog",
  "Shiniers",
  "Shiniest",
  "Shiniest Hound",
  "Shiniest Mastiff",
  "Shiniest Pointer",
  "Shiniest Setter",
  "Shiniest Sheepdog",
  "Shiniest Spaniel",
  "Shiniest Terrier",
  "Shiniest Water Dog",
  "Shiniester",
  "Shiniester Hound",
  "Shiniester Mastiff",
  "Shiniester Pointer",
  "Shiniester Setter",
  "Shiniester Sheepdog",
  "Shiniester Spaniel",
  "Shiniester Terrier",
  "Shiniester Water Dog",
  "Shiniesterone",
  "Shiniestly",
  "Shiniestli",
  "Shiniestlie",
  "Shiniestness",
  "Shiniestness Hound",
  "Shiniestness Mastiff",
  "Shiniestness Pointer",
  "Shiniestness Setter",
  "Shiniestness Sheepdog",
  "Shiniestness Spaniel",
  "Shiniestness Terrier",
  "Shiniestness Water Dog",
  "Shiniestnesses",
  "Shiniestnesses Hound",
  "Shiniestnesses Mastiff",
  "Shiniestnesses Pointer",
  "Shiniestnesses Setter",
  "Shiniestnesses Sheepdog",
  "Shiniestnesses Spaniel",
  "Shiniestnesses Terrier",
  "Shiniestnesses Water Dog",
  "Shinieth",
  "Shinieth Hound",
  "Shinieth Mastiff",
  "Shinieth Pointer",
  "Shinieth Setter",
  "Shinieth Sheepdog",
  "Shinieth Spaniel",
  "Shinieth Terrier",
  "Shinieth Water Dog",
  "Shiniethly",
  "Shining Dog",
  "Shining Hound",
  "Shining Mastiff",
  "Shining Pointer",
  "Shining Setter",
  "Shining Sheepdog",
  "Shining Spaniel",
  "Shining Terrier",
  "Shining Water Dog",
  "Shiningly",
  "Shiningly Hound",
  "Shiningly Mastiff",
  "Shiningly Pointer",
  "Shiningly Setter",
  "Shiningly Sheepdog",
  "Shiningly Spaniel",
  "Shiningly Terrier",
  "Shiningly Water Dog",
  "Shiningess",
  "Shiningess Hound",
  "Shiningess Mastiff",
  "Shiningess Pointer",
  "Shiningess Setter",
  "Shiningess Sheepdog",
  "Shiningess Spaniel",
  "Shiningess Terrier",
  "Shiningess Water Dog",
  "Shiningesses",
  "Shiningesses Hound",
  "Shiningesses Mastiff",
  "Shiningesses Pointer",
  "Shiningesses Setter",
  "Shiningesses Sheepdog",
  "Shiningesses Spaniel",
  "Shiningesses Terrier",
  "Shiningesses Water Dog",
  "Shingos",
  "Shingos Hound",
  "Shingos Mastiff",
  "Shingos Pointer",
  "Shingos Setter",
  "Shingos Sheepdog",
  "Shingos Spaniel",
  "Shingos Terrier",
  "Shingos Water Dog",
  "Shingos's",
  "Shinier",
  "Shino",
  "Shinola",
  "Shinola Hound",
  "Shinola Mastiff",
  "Shinola Pointer",
  "Shinola Setter",
  "Shinola Sheepdog",
  "Shinola Spaniel",
  "Shinola Terrier",
  "Shinola Water Dog",
  "Shinolas",
  "Shinolas Hound",
  "Shinolas Mastiff",
  "Shinolas Pointer",
  "Shinolas Setter",
  "Shinolas Sheepdog",
  "Shinolas Spaniel",
  "Shinolas Terrier",
  "Shinolas Water Dog",
  "Shinolaed",
  "Shinolaed Hound",
  "Shinolaed Mastiff",
  "Shinolaed Pointer",
  "Shinolaed Setter",
  "Shinolaed Sheepdog",
  "Shinolaed Spaniel",
  "Shinolaed Terrier",
  "Shinolaed Water Dog",
  "Shinolaer",
  "Shinolaers",
  "Shinolaers Hound",
  "Shinolaers Mastiff",
  "Shinolaers Pointer",
  "Shinolaers Setter",
  "Shinolaers Sheepdog",
  "Shinolaers Spaniel",
  "Shinolaers Terrier",
  "Shinolaers Water Dog",
  "Shinolaing",
  "Shinolaing Hound",
  "Shinolaing Mastiff",
  "Shinolaing Pointer",
  "Shinolaing Setter",
  "Shinolaing Sheepdog",
  "Shinolaing Spaniel",
  "Shinolaing Terrier",
  "Shinolaing Water Dog",
  "Shinolaings",
  "Shinolaings Hound",
  "Shinolaings Mastiff",
  "Shinolaings Pointer",
  "Shinolaings Setter",
  "Shinolaings Sheepdog",
  "Shinolaings Spaniel",
  "Shinolaings Terrier",
  "Shinolaings Water Dog",
  "Shinolaingly",
  "Shinolaingly Hound",
  "Shinolaingly Mastiff",
  "Shinolaingly Pointer",
  "Shinolaingly Setter",
  "Shinolaingly Sheepdog",
  "Shinolaingly Spaniel",
  "Shinolaingly Terrier",
  "Shinolaingly Water Dog",
  "Shinolaingess",
  "Shinolaingess Hound",
  "Shinolaingess Mastiff",
  "Shinolaingess Pointer",
  "Shinolaingess Setter",
  "Shinolaingess Sheepdog",
  "Shinolaingess Spaniel",
  "Shinolaingess Terrier",
  "Shinolaingess Water Dog",
  "Shinolaingesses",
  "Shinolaingesses Hound",
  "Shinolaingesses Mastiff",
  "Shinolaingesses Pointer",
  "Shinolaingesses Setter",
  "Shinolaingesses Sheepdog",
  "Shinolaingesses Spaniel",
  "Shinolaingesses Terrier",
  "Shinolaingesses Water Dog",
  "Shinolaish",
  "Shinolaish Hound",
  "Shinolaish Mastiff",
  "Shinolaish Pointer",
  "Shinolaish Setter",
  "Shinolaish Sheepdog",
  "Shinolaish Spaniel",
  "Shinolaish Terrier",
  "Shinolaish Water Dog",
  "Shinolaishly",
  "Shinolaishly Hound",
  "Shinolaishly Mastiff",
  "Shinolaishly Pointer",
  "Shinolaishly Setter",
  "Shinolaishly Sheepdog",
  "Shinolaishly Spaniel",
  "Shinolaishly Terrier",
  "Shinolaishly Water Dog",
  "Shinolaishness",
  "Shinolaishness Hound",
  "Shinolaishness Mastiff",
  "Shinolaishness Pointer",
  "Shinolaishness Setter",
  "Shinolaishness Sheepdog",
  "Shinolaishness Spaniel",
  "Shinolaishness Terrier",
  "Shinolaishness Water Dog",
  "Shinolaishnesses",
  "Shinolaishnesses Hound",
  "Shinolaishnesses Mastiff",
  "Shinolaishnesses Pointer",
  "Shinolaishnesses Setter",
  "Shinolaishnesses Sheepdog",
  "Shinolaishnesses Spaniel",
  "Shinolaishnesses Terrier",
  "Shinolaishnesses Water Dog",
  "Siberian Husky",
  "Sicilian Hound",
  "Sighthound",
  "Silken Windhound",
  "Silky Terrier",
  "Simmentaler",
  "Simulance",
  "Simulance Hound",
  "Simulance Mastiff",
  "Simulance Pointer",
  "Simulance Setter",
  "Simulance Sheepdog",
  "Simulance Spaniel",
  "Simulance Terrier",
  "Simulance Water Dog",
  "Simulances",
  "Simulances Hound",
  "Simulances Mastiff",
  "Simulances Pointer",
  "Simulances Setter",
  "Simulances Sheepdog",
  "Simulances Spaniel",
  "Simulances Terrier",
  "Simulances Water Dog",
  "Simulances's",
  "Simulant",
  "Simulant Hound",
  "Simulant Mastiff",
  "Simulant Pointer",
  "Simulant Setter",
  "Simulant Sheepdog",
  "Simulant Spaniel",
  "Simulant Terrier",
  "Simulant Water Dog",
  "Simulantism",
  "Simulantism Hound",
  "Simulantism Mastiff",
  "Simulantism Pointer",
  "Simulantism Setter",
  "Simulantism Sheepdog",
  "Simulantism Spaniel",
  "Simulantism Terrier",
  "Simulantism Water Dog",
  "Simulantisms",
  "Simulantisms Hound",
  "Simulantisms Mastiff",
  "Simulantisms Pointer",
  "Simulantisms Setter",
  "Simulantisms Sheepdog",
  "Simulantisms Spaniel",
  "Simulantisms Terrier",
  "Simulantisms Water Dog",
  "Simulantismic",
  "Simulantismic Hound",
  "Simulantismic Mastiff",
  "Simulantismic Pointer",
  "Simulantismic Setter",
  "Simulantismic Sheepdog",
  "Simulantismic Spaniel",
  "Simulantismic Terrier",
  "Simulantismic Water Dog",
  "Simulantismical",
  "Simulantismical Hound",
  "Simulantismical Mastiff",
  "Simulantismical Pointer",
  "Simulantismical Setter",
  "Simulantismical Sheepdog",
  "Simulantismical Spaniel",
  "Simulantismical Terrier",
  "Simulantismical Water Dog",
  "Simulantismically",
  "Simulantismically Hound",
  "Simulantismically Mastiff",
  "Simulantismically Pointer",
  "Simulantismically Setter",
  "Simulantismically Sheepdog",
  "Simulantismically Spaniel",
  "Simulantismically Terrier",
  "Simulantismically Water Dog",
  "Simulantist",
  "Simulantist Hound",
  "Simulantist Mastiff",
  "Simulantist Pointer",
  "Simulantist Setter",
  "Simulantist Sheepdog",
  "Simulantist Spaniel",
  "Simulantist Terrier",
  "Simulantist Water Dog",
  "Simulantists",
  "Simulantists Hound",
  "Simulantists Mastiff",
  "Simulantists Pointer",
  "Simulantists Setter",
  "Simulantists Sheepdog",
  "Simulantists Spaniel",
  "Simulantists Terrier",
  "Simulantists Water Dog",
  "Simulantistic",
  "Simulantistic Hound",
  "Simulantistic Mastiff",
  "Simulantistic Pointer",
  "Simulantistic Setter",
  "Simulantistic Sheepdog",
  "Simulantistic Spaniel",
  "Simulantistic Terrier",
  "Simulantistic Water Dog",
  "Simulantistical",
  "Simulantistical Hound",
  "Simulantistical Mastiff",
  "Simulantistical Pointer",
  "Simulantistical Setter",
  "Simulantistical Sheepdog",
  "Simulantistical Spaniel",
  "Simulantistical Terrier",
  "Simulantistical Water Dog",
  "Simulantistically",
  "Simulantistical Hound",
  "Simulantistically Mastiff",
  "Simulantistically Pointer",
  "Simulantistically Setter",
  "Simulantistically Sheepdog",
  "Simulantistically Spaniel",
  "Simulantistically Terrier",
  "Simulantistically Water Dog",
  "Simulants",
  "Simulants Hound",
  "Simulants Mastiff",
  "Simulants Pointer",
  "Simulants Setter",
  "Simulants Sheepdog",
  "Simulants Spaniel",
  "Simulants Terrier",
  "Simulants Water Dog",
  "Simulants's",
  "Sire",
  "Sire Dog",
  "Sired",
  "Sired Hound",
  "Sired Mastiff",
  "Sired Pointer",
  "Sired Setter",
  "Sired Sheepdog",
  "Sired Spaniel",
  "Sired Terrier",
  "Sired Water Dog",
  "Sirer",
  "Sirers",
  "Sirers Hound",
  "Sirers Mastiff",
  "Sirers Pointer",
  "Sirers Setter",
  "Sirers Sheepdog",
  "Sirers Spaniel",
  "Sirers Terrier",
  "Sirers Water Dog",
  "Sires",
  "Sires Hound",
  "Sires Mastiff",
  "Sires Pointer",
  "Sires Setter",
  "Sires Sheepdog",
  "Sires Spaniel",
  "Sires Terrier",
  "Sires Water Dog",
  "Siring",
  "Siring Hound",
  "Siring Mastiff",
  "Siring Pointer",
  "Siring Setter",
  "Siring Sheepdog",
  "Siring Spaniel",
  "Siring Terrier",
  "Siring Water Dog",
  "Sirings",
  "Sirings Hound",
  "Sirings Mastiff",
  "Sirings Pointer",
  "Sirings Setter",
  "Sirings Sheepdog",
  "Sirings Spaniel",
  "Sirings Terrier",
  "Sirings Water Dog",
  "Siringly",
  "Siringly Hound",
  "Siringly Mastiff",
  "Siringly Pointer",
  "Siringly Setter",
  "Siringly Sheepdog",
  "Siringly Spaniel",
  "Siringly Terrier",
  "Siringly Water Dog",
  "Skipper Terrier",
  "Skye Terrier",
  "Skyefold",
  "Smooth Coat Chihuahua",
  "Smooth Collie",
  "Smooth Fox Terrier",
  "Snoopy",
  "Snoopy Hound",
  "Snoopy Mastiff",
  "Snoopy Pointer",
  "Snoopy Setter",
  "Snoopy Sheepdog",
  "Snoopy Spaniel",
  "Snoopy Terrier",
  "Snoopy Water Dog",
  "Snowdrop",
  "Snowdrop Hound",
  "Snowdrop Mastiff",
  "Snowdrop Pointer",
  "Snowdrop Setter",
  "Snowdrop Sheepdog",
  "Snowdrop Spaniel",
  "Snowdrop Terrier",
  "Snowdrop Water Dog",
  "Soft Coated Wheaten Terrier",
  "Somali Mastiff",
  "Somali Pointer",
  "Somali Setter",
  "Somali Sheepdog",
  "Somali Spaniel",
  "Somali Terrier",
  "Somali Water Dog",
  "Somali Hound",
  "Spanish Mastiff",
  "Spanish Pointer",
  "Spanish Setter",
  "Spanish Sheepdog",
  "Spanish Spaniel",
  "Spanish Terrier",
  "Spanish Water Dog",
  "Spanish Hound",
  "Spaniel",
  "Spaniel-Setter Mix",
  "Spaniel-Pointer Mix",
  "Spaniel-Retriever Mix",
  "Spaniel-Terrier Mix",
  "Spaniel-Water Dog Mix",
  "Spaniels",
  "Spaniels Hound",
  "Spaniels Mastiff",
  "Spaniels Pointer",
  "Spaniels Setter",
  "Spaniels Sheepdog",
  "Spaniels Terrier",
  "Spaniels Water Dog",
  "Spars",
  "Spars Hound",
  "Spars Mastiff",
  "Spars Pointer",
  "Spars Setter",
  "Spars Sheepdog",
  "Spars Spaniel",
  "Spars Terrier",
  "Spars Water Dog",
  "Spartan Hound",
  "Spartan Mastiff",
  "Spartan Pointer",
  "Spartan Setter",
  "Spartan Sheepdog",
  "Spartan Spaniel",
  "Spartan Terrier",
  "Spartan Water Dog",
  "Spartans Hound",
  "Spartans Mastiff",
  "Spartans Pointer",
  "Spartans Setter",
  "Spartans Sheepdog",
  "Spartans Spaniel",
  "Spartans Terrier",
  "Spartans Water Dog",
  "Spaulding Hound",
  "Spaulding Mastiff",
  "Spaulding Pointer",
  "Spaulding Setter",
  "Spaulding Sheepdog",
  "Spaulding Spaniel",
  "Spaulding Terrier",
  "Spaulding Water Dog",
  "Speaight Hound",
  "Speaight Mastiff",
  "Speaight Pointer",
  "Speaight Setter",
  "Speaight Sheepdog",
  "Speaight Spaniel",
  "Speaight Terrier",
  "Speaight Water Dog",
  "Spear Hound",
  "Spear Mastiff",
  "Spear Pointer",
  "Spear Setter",
  "Spear Sheepdog",
  "Spear Spaniel",
  "Spear Terrier",
  "Spear Water Dog",
  "Speary Hound",
  "Speary Mastiff",
  "Speary Pointer",
  "Speary Setter",
  "Speary Sheepdog",
  "Speary Spaniel",
  "Speary Terrier",
  "Speary Water Dog",
  "Specker Hound",
  "Specker Mastiff",
  "Specker Pointer",
  "Specker Setter",
  "Specker Sheepdog",
  "Specker Spaniel",
  "Specker Terrier",
  "Specker Water Dog",
  "Speckhund",
  "Speckhund Hound",
  "Speckhund Mastiff",
  "Speckhund Pointer",
  "Speckhund Setter",
  "Speckhund Sheepdog",
  "Speckhund Spaniel",
  "Speckhund Terrier",
  "Speckhund Water Dog",
  "Speckhunds",
  "Speckhunds Hound",
  "Speckhunds Mastiff",
  "Speckhunds Pointer",
  "Speckhunds Setter",
  "Speckhunds Sheepdog",
  "Speckhunds Spaniel",
  "Speckhunds Terrier",
  "Speckhunds Water Dog",
  "Speckier",
  "Speckier Hound",
  "Speckier Mastiff",
  "Speckier Pointer",
  "Speckier Setter",
  "Speckier Sheepdog",
  "Speckier Spaniel",
  "Speckier Terrier",
  "Speckier Water Dog",
  "Speckiest",
  "Speckiest Hound",
  "Speckiest Mastiff",
  "Speckiest Pointer",
  "Speckiest Setter",
  "Speckiest Sheepdog",
  "Speckiest Spaniel",
  "Speckiest Terrier",
  "Speckiest Water Dog",
  "Speckily",
  "Speckily Hound",
  "Speckily Mastiff",
  "Speckily Pointer",
  "Speckily Setter",
  "Speckily Sheepdog",
  "Speckily Spaniel",
  "Speckily Terrier",
  "Speckily Water Dog",
  "Speckily's",
  "Speckily's Hound",
  "Speckily's Mastiff",
  "Speckily's Pointer",
  "Speckily's Setter",
  "Speckily's Sheepdog",
  "Speckily's Spaniel",
  "Speckily's Terrier",
  "Speckily's Water Dog",
  "Speckiness",
  "Speckiness Hound",
  "Speckiness Mastiff",
  "Speckiness Pointer",
  "Speckiness Setter",
  "Speckiness Sheepdog",
  "Speckiness Spaniel",
  "Speckiness Terrier",
  "Speckiness Water Dog",
  "Speckinesses",
  "Speckinesses Hound",
  "Speckinesses Mastiff",
  "Speckinesses Pointer",
  "Speckinesses Setter",
  "Speckinesses Sheepdog",
  "Speckinesses Spaniel",
  "Speckinesses Terrier",
  "Speckinesses Water Dog",
  "Speckled",
  "Speckled Hound",
  "Speckled Mastiff",
  "Speckled Pointer",
  "Speckled Setter",
  "Speckled Sheepdog",
  "Speckled Spaniel",
  "Speckled Terrier",
  "Speckled Water Dog",
  "Speckling",
  "Speckling Hound",
  "Speckling Mastiff",
  "Speckling Pointer",
  "Speckling Setter",
  "Speckling Sheepdog",
  "Speckling Spaniel",
  "Speckling Terrier",
  "Speckling Water Dog",
  "Specklings",
  "Specklings Hound",
  "Specklings Mastiff",
  "Specklings Pointer",
  "Specklings Setter",
  "Specklings Sheepdog",
  "Specklings Spaniel",
  "Specklings Terrier",
  "Specklings Water Dog",
  "Specks",
  "Specks Hound",
  "Specks Mastiff",
  "Specks Pointer",
  "Specks Setter",
  "Specks Sheepdog",
  "Specks Spaniel",
  "Specks Terrier",
  "Specks Water Dog",
  "Specky",
  "Specky Hound",
  "Specky Mastiff",
  "Specky Pointer",
  "Specky Setter",
  "Specky Sheepdog",
  "Specky Spaniel",
  "Specky Terrier",
  "Specky Water Dog",
  "Specky's",
  "St. Bernard",
  "St. Bernard Water Dog",
  "Staffordshire Bull Terrier",
  "Staffordshire Terrier",
  "Stag Hound",
  "Stag Mastiff",
  "Stag Pointer",
  "Stag Setter",
  "Stag Sheepdog",
  "Stag Spaniel",
  "Stag Terrier",
  "Stag Water Dog",
  "Staffordshire",
  "Staffordshire Hound",
  "Staffordshire Mastiff",
  "Staffordshire Pointer",
  "Staffordshire Setter",
  "Staffordshire Sheepdog",
  "Staffordshire Spaniel",
  "Staffordshire Terrier",
  "Staffordshire Water Dog",
  "Staffordshires",
  "Staffordshires Hound",
  "Staffordshires Mastiff",
  "Staffordshires Pointer",
  "Staffordshires Setter",
  "Staffordshires Sheepdog",
  "Staffordshires Spaniel",
  "Staffordshires Terrier",
  "Staffordshires Water Dog",
  "Staghound",
  "Staghound Hound",
  "Staghound Mastiff",
  "Staghound Pointer",
  "Staghound Setter",
  "Staghound Sheepdog",
  "Staghound Spaniel",
  "Staghound Terrier",
  "Staghound Water Dog",
  "Staghounds",
  "Staghounds Hound",
  "Staghounds Mastiff",
  "Staghounds Pointer",
  "Staghounds Setter",
  "Staghounds Sheepdog",
  "Staghounds Spaniel",
  "Staghounds Terrier",
  "Staghounds Water Dog",
  "Stain",
  "Stain Hound",
  "Stain Mastiff",
  "Stain Pointer",
  "Stain Setter",
  "Stain Sheepdog",
  "Stain Spaniel",
  "Stain Terrier",
  "Stain Water Dog",
  "Stained",
  "Stained Hound",
  "Stained Mastiff",
  "Stained Pointer",
  "Stained Setter",
  "Stained Sheepdog",
  "Stained Spaniel",
  "Stained Terrier",
  "Stained Water Dog",
  "Stainer",
  "Stainer Hound",
  "Stainer Mastiff",
  "Stainer Pointer",
  "Stainer Setter",
  "Stainer Sheepdog",
  "Stainer Spaniel",
  "Stainer Terrier",
  "Stainer Water Dog",
  "Stainers",
  "Stainers Hound",
  "Stainers Mastiff",
  "Stainers Pointer",
  "Stainers Setter",
  "Stainers Sheepdog",
  "Stainers Spaniel",
  "Stainers Terrier",
  "Stainers Water Dog",
  "Stainful",
  "Stainful Hound",
  "Stainful Mastiff",
  "Stainful Pointer",
  "Stainful Setter",
  "Stainful Sheepdog",
  "Stainful Spaniel",
  "Stainful Terrier",
  "Stainful Water Dog",
  "Stainfully",
  "Stainfully Hound",
  "Stainfully Mastiff",
  "Stainfully Pointer",
  "Stainfully Setter",
  "Stainfully Sheepdog",
  "Stainfully Spaniel",
  "Stainfully Terrier",
  "Stainfully Water Dog",
  "Stainfulness",
  "Stainfulness Hound",
  "Stainfulness Mastiff",
  "Stainfulness Pointer",
  "Stainfulness Setter",
  "Stainfulness Sheepdog",
  "Stainfulness Spaniel",
  "Stainfulness Terrier",
  "Stainfulness Water Dog",
  "Stainfulnesses",
  "Stainfulnesses Hound",
  "Stainfulnesses Mastiff",
  "Stainfulnesses Pointer",
  "Stainfulnesses Setter",
  "Stainfulnesses Sheepdog",
  "Stainfulnesses Spaniel",
  "Stainfulnesses Terrier",
  "Stainfulnesses Water Dog",
  "Staining",
  "Staining Hound",
  "Staining Mastiff",
  "Staining Pointer",
  "Staining Setter",
  "Staining Sheepdog",
  "Staining Spaniel",
  "Staining Terrier",
  "Staining Water Dog",
  "Stainings",
  "Stainings Hound",
  "Stainings Mastiff",
  "Stainings Pointer",
  "Stainings Setter",
  "Stainings Sheepdog",
  "Stainings Spaniel",
  "Stainings Terrier",
  "Stainings Water Dog",
  "Stainingly",
  "Stainingly Hound",
  "Stainingly Mastiff",
  "Stainingly Pointer",
  "Stainingly Setter",
  "Stainingly Sheepdog",
  "Stainingly Spaniel",
  "Stainingly Terrier",
  "Stainingly Water Dog",
  "Stainless",
  "Stainless Hound",
  "Stainless Mastiff",
  "Stainless Pointer",
  "Stainless Setter",
  "Stainless Sheepdog",
  "Stainless Spaniel",
  "Stainless Terrier",
  "Stainless Water Dog",
  "Stainlessly",
  "Stainlessly Hound",
  "Stainlessly Mastiff",
  "Stainlessly Pointer",
  "Stainlessly Setter",
  "Stainlessly Sheepdog",
  "Stainlessly Spaniel",
  "Stainlessly Terrier",
  "Stainlessly Water Dog",
  "Stainlessness",
  "Stainlessness Hound",
  "Stainlessness Mastiff",
  "Stainlessness Pointer",
  "Stainlessness Setter",
  "Stainlessness Sheepdog",
  "Stainlessness Spaniel",
  "Stainlessness Terrier",
  "Stainlessness Water Dog",
  "Stainlessnesses",
  "Stainlessnesses Hound",
  "Stainlessnesses Mastiff",
  "Stainlessnesses Pointer",
  "Stainlessnesses Setter",
  "Stainlessnesses Sheepdog",
  "Stainlessnesses Spaniel",
  "Stainlessnesses Terrier",
  "Stainlessnesses Water Dog",
];

export function DogBreedDropdown({ value, onSelect, isDark }: DogBreedDropdownProps) {
  const { theme } = useTheme();
  const [showDropdown, setShowDropdown] = useState(false);

  const filteredBreeds = useMemo(() => {
    if (!value.trim()) return POPULAR_BREEDS;
    return POPULAR_BREEDS.filter((breed) =>
      breed.toLowerCase().includes(value.toLowerCase())
    );
  }, [value]);

  const handleSelectBreed = (breed: string) => {
    onSelect(breed);
    setShowDropdown(false);
  };

  const handleInputChange = (text: string) => {
    onSelect(text);
    if (text.length > 0) {
      setShowDropdown(true);
    } else {
      setShowDropdown(false);
    }
  };

  return (
    <View style={styles.wrapper}>
      <TextInput
        style={[
          styles.input,
          {
            backgroundColor: theme.backgroundDefault,
            color: theme.text,
            borderColor: theme.borderLight,
          },
        ]}
        value={value}
        onChangeText={handleInputChange}
        onFocus={() => value.length > 0 && setShowDropdown(true)}
        onBlur={() => setTimeout(() => setShowDropdown(false), 100)}
        placeholder="Start typing a breed..."
        placeholderTextColor={isDark ? "#9BA1A6" : "#6E6E6E"}
        autoCapitalize="words"
      />

      {showDropdown && filteredBreeds.length > 0 && (
        <ScrollView
          nestedScrollEnabled={true}
          style={[
            styles.dropdown,
            {
              backgroundColor: theme.backgroundDefault,
              borderColor: theme.borderLight,
            },
          ]}
          scrollEnabled={filteredBreeds.length > 6}
        >
          {filteredBreeds.map((breed, index) => (
            <Pressable
              key={breed}
              onPress={() => handleSelectBreed(breed)}
              style={[
                styles.option,
                {
                  backgroundColor:
                    value === breed ? Colors.light.primary + "20" : "transparent",
                  borderBottomColor: theme.borderLight,
                  borderBottomWidth: index < filteredBreeds.length - 1 ? 1 : 0,
                },
              ]}
            >
              <ThemedText type="body" style={styles.optionText}>
                {breed}
              </ThemedText>
            </Pressable>
          ))}
        </ScrollView>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  wrapper: {
    width: "100%",
    zIndex: 1000,
  },
  input: {
    height: Spacing.inputHeight,
    borderWidth: 1,
    borderRadius: BorderRadius.md,
    paddingHorizontal: Spacing.md,
    fontSize: Typography.bodyM.fontSize,
  },
  dropdown: {
    marginTop: Spacing.xs,
    borderWidth: 1,
    borderRadius: BorderRadius.md,
    maxHeight: 220,
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  option: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
  },
  optionText: {
    fontSize: Typography.bodyM.fontSize,
  },
});
